# Generated by Django 5.1.5 on 2026-04-19

import django.db.models.deletion
import diagnosis.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'F\xe9minin'), ('O', 'Autre')], max_length=1)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('xray_image', models.ImageField(upload_to=diagnosis.models.upload_to_patient)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('ai_prediction', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('all_probabilities', models.JSONField(blank=True, default=dict)),
                ('validated', models.BooleanField(default=False)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('final_diagnosis', models.TextField(blank=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-upload_date'],
            },
        ),
    ]
